//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.31 at 02:31:25 AM EET 
//


package ua.kiev.unicyb.courses.project3.devices.model.devices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.model.devices.device package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Devices_QNAME = new QName("http://devices.com/Device", "ua/kiev/unicyb/courses/project3/devices/model/devices");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.kiev.unicyb.courses.project3.devices.model.devices.device
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeDevices }
     * 
     */
    public TypeDevices createTypeDevices() {
        return new TypeDevices();
    }

    /**
     * Create an instance of {@link TType }
     * 
     */
    public TType createTType() {
        return new TType();
    }

    /**
     * Create an instance of {@link TypeDevices.Device }
     * 
     */
    public TypeDevices.Device createTypeDevicesDevice() {
        return new TypeDevices.Device();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeDevices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://devices.com/Device", name = "ua/kiev/unicyb/courses/project3/devices/model/devices")
    public JAXBElement<TypeDevices> createDevices(TypeDevices value) {
        return new JAXBElement<TypeDevices>(_Devices_QNAME, TypeDevices.class, null, value);
    }

}
