//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.31 at 02:31:25 AM EET 
//


package ua.kiev.unicyb.courses.project3.devices.model.devices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for originType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="originType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Ukraine"/>
 *     &lt;enumeration value="China"/>
 *     &lt;enumeration value="USA"/>
 *     &lt;enumeration value="Germany"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "originType")
@XmlEnum
public enum OriginType {

    @XmlEnumValue("Ukraine")
    UKRAINE("Ukraine"),
    @XmlEnumValue("China")
    CHINA("China"),
    USA("USA"),
    @XmlEnumValue("Germany")
    GERMANY("Germany");
    private final String value;

    OriginType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OriginType fromValue(String v) {
        for (OriginType c: OriginType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
