//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.31 at 02:31:25 AM EET 
//


package ua.kiev.unicyb.courses.project3.devices.model.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typePorts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typePorts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="COM" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="USB" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="LPT" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typePorts", propOrder = {
    "com",
    "usb",
    "lpt"
})
public class TypePorts {

    @XmlElement(name = "COM")
    protected boolean com;
    @XmlElement(name = "USB")
    protected boolean usb;
    @XmlElement(name = "LPT")
    protected boolean lpt;

    /**
     * Gets the value of the com property.
     * 
     */
    public boolean isCOM() {
        return com;
    }

    /**
     * Sets the value of the com property.
     * 
     */
    public void setCOM(boolean value) {
        this.com = value;
    }

    /**
     * Gets the value of the usb property.
     * 
     */
    public boolean isUSB() {
        return usb;
    }

    /**
     * Sets the value of the usb property.
     * 
     */
    public void setUSB(boolean value) {
        this.usb = value;
    }

    /**
     * Gets the value of the lpt property.
     * 
     */
    public boolean isLPT() {
        return lpt;
    }

    /**
     * Sets the value of the lpt property.
     * 
     */
    public void setLPT(boolean value) {
        this.lpt = value;
    }

    @Override
    public String toString() {
        return "TypePorts{" +
                "com=" + com +
                ", usb=" + usb +
                ", lpt=" + lpt +
                '}';
    }
}
